plugins-path: '/var/lib/gems/2.3.0/gems/nanoci-0.1.0/lib/nanoci/plugins'
repo-cache: '/home/nanoci/workdir/repo-cache'
build-data-dir: '/home/nanoci/workdir/builds'
capabilities:
  - 'tools.git': '/usr/bin/git'
  - 'tools.ssh': '/usr/bin/ssh'
  - 'tools.rspec': '/usr/local/bin/rspec'
agents:
  - name: 'Local Agent #1'
    workdir: '/home/nanoci/workdir/agents/agent-1'
mongo-connection-string: mongodb://172.28.128.3:27017/nanoci
