Vagrant.configure('2') do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

	config.vm.box = 'ubuntu/xenial64'
	config.vm.hostname = 'nano-ci-service.thevk.net'

	config.vm.network 'private_network', ip: '172.28.128.4'

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
		apt-get install -y ruby ruby-dev build-essential git
		useradd -m nanoci
		mkdir /home/nanoci/workdir
		gem install /vagrant/nanoci-0.1.0.gem
		gem install rspec
		cp /vagrant/nanoci.key /home/nanoci
		chown nanoci:nanoci /home/nanoci -R
		chmod 400 /home/nanoci/nanoci.key
		cp /vagrant/nano-ci.service /lib/systemd/system
		chmod -x /lib/systemd/system/nano-ci.service
		cp /vagrant/40-nano-ci.conf /etc/rsyslog.d/
		chmod -x /etc/rsyslog.d/40-nano-ci.conf
		service rsyslog restart
		service nano-ci start
  SHELL
end
