# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = 'ubuntu/xenial64'

  config.vm.network 'forwarded_port', guest: 27017, host: 27017, host_ip: '127.0.0.1'

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
		apt-get install -y mongodb
		sed -i 's/bind_ip.*/bind_ip = 0\.0\.0\.0/' /etc/mongodb.conf
		sed -i 's/#port.*/port = 27017/' /etc/mongodb.conf
		service mongodb restart
  SHELL
end
