# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: agent_manager.proto for package 'nanociRemote'

require 'grpc'
require 'agent_manager_pb'

module NanociRemote
  module AgentManager
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'nanociRemote.AgentManager'

      rpc :ReportAgentStatus, ReportAgentStatusRequest, ReportAgentStatusResponse
    end

    Stub = Service.rpc_stub_class
  end
end
