# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "nanociRemote.AgentStatus" do
    value :UNKNOWN, 0
    value :IDLE, 1
    value :BUSY, 2
  end
end

module NanociRemote
  AgentStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanociRemote.AgentStatus").enummodule
end
