# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_agent_service.proto

require 'google/protobuf'

require 'report_agent_status_message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module NanociRemote
end
