# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: remote_agent_service.proto for package 'nanociRemote'

require 'grpc'
require 'remote_agent_service_pb'

module NanociRemote
  module RemoteAgentService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'nanociRemote.RemoteAgentService'

      rpc :ReportAgentStatus, ReportAgentStatusRequest, ReportAgentStatusResponse
    end

    Stub = Service.rpc_stub_class
  end
end
