# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report_agent_status_message.proto

require 'google/protobuf'

require 'agent_status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "nanociRemote.ReportAgentStatusRequest" do
    optional :agent_tag, :string, 1
    optional :agent_status, :enum, 2, "nanociRemote.AgentStatus"
    repeated :agent_capabilities, :string, 3
  end
  add_message "nanociRemote.ReportAgentStatusResponse" do
  end
end

module NanociRemote
  ReportAgentStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanociRemote.ReportAgentStatusRequest").msgclass
  ReportAgentStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanociRemote.ReportAgentStatusResponse").msgclass
end
