plugins-path: 'lib/nanoci/plugins'
repo-cache: 'C:/nano-ci/repo-cache'
build-data-dir: 'C:/nano-ci/builds'
capabilities:
  - 'tools.git': 'C:/Program Files/Git/cmd/git.exe'
  - 'tools.ssh': 'C:/ProgramData/Chocolatey/bin/PLINK.EXE'
  - 'tools.rspec': 'C:/tools/Ruby25-x64/bin\rspec.bat'
agents:
  - name: 'Local Agent #1'
    workdir: 'c:/nano-ci/agents/agent-1'
mongo-connection-string: mongodb://127.0.0.1:27017/nanoci
