plugins-path: 'lib/nanoci/plugins'
repo-cache: 'C:/nano-ci/repo-cache'
capabilities:
  - 'tools.git': 'C:\Program Files\Git\cmd\git.exe'
agents:
  - name: 'Local Agent #1'
    workdir: 'c:/nano-ci/agents/agent-1'
