plugins-path: 'lib/nanoci/plugins'
repo-cache: 'C:/nano-ci/repo-cache'
logdir: 'c:/nano-ci/logs'
capabilities:
  - 'tools.git': 'C:\Program Files\Git\cmd\git.exe'
agents:
  - name: 'Local Agent #1'
    workdir: 'c:/nano-ci/agents/agent-1'
mongo-connection-string: mongodb://127.0.0.1:27017/nanoci
