build-data-dir: /var/nano-ci/builds-data

db:
  provider: 'ram'
  mongo:
    clients:
      default:
        database: "nano-ci-dev"
        hosts: [localhost:27017]
        options:
          app_name: "nano-ci"
