# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent_manager.proto

require 'google/protobuf'

require 'report_agent_status_message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Nanoci
  module Remote
  end
end
