# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_state.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum 'nanoci.remote.job_state.JobState' do
    value :UNKNOWN, 0
    value :QUEUED, 1
    value :PENDING, 2
    value :RUNNING, 3
    value :ABORTED, 4
    value :FAILED, 5
    value :COMPLETED, 6
  end
end

module Nanoci
  module Remote
    module JobState
      JobState = Google::Protobuf::DescriptorPool.generated_pool.lookup('nanoci.remote.job_state.JobState').enummodule
    end
  end
end
