# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_state.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "nanoci.remote.JobState" do
    value :JS_UNKNOWN, 0
    value :JS_QUEUED, 1
    value :JS_PENDING, 2
    value :JS_RUNNING, 3
    value :JS_ABORTED, 4
    value :JS_FAILED, 5
    value :JS_COMPLETED, 6
  end
end

module Nanoci
  module Remote
    JobState = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanoci.remote.JobState").enummodule
  end
end
