# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_agent_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "nanoci.remote.ReportAgentStatusRequest" do
    optional :agent_name, :string, 1
    optional :agent_status, :enum, 2, "nanoci.remote.AgentStatus"
  end
  add_message "nanoci.remote.ReportAgentStatusResponse" do
  end
  add_enum "nanoci.remote.AgentStatus" do
    value :UNKNOWN, 0
    value :IDLE, 1
    value :BUSY, 2
  end
end

module Nanoci
  module Remote
    ReportAgentStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanoci.remote.ReportAgentStatusRequest").msgclass
    ReportAgentStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanoci.remote.ReportAgentStatusResponse").msgclass
    AgentStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanoci.remote.AgentStatus").enummodule
  end
end
