# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: remote_agent_service.proto for package 'nanoci.remote'

require 'grpc'
require 'remote_agent_service_pb'

module Nanoci
  module Remote
    module RemoteAgentService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'nanoci.remote.RemoteAgentService'

        rpc :ReportAgentStatus, ReportAgentStatusRequest, ReportAgentStatusResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
