# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report_agent_status_message.proto

require 'google/protobuf'

require 'agent_status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "nanoci.remote.ReportAgentStatusRequest" do
    optional :agent_tag, :string, 1
    optional :agent_status, :enum, 2, "nanoci.remote.AgentStatus"
    repeated :agent_capabilities, :string, 3
  end
  add_message "nanoci.remote.ReportAgentStatusResponse" do
  end
end

module Nanoci
  module Remote
    ReportAgentStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanoci.remote.ReportAgentStatusRequest").msgclass
    ReportAgentStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("nanoci.remote.ReportAgentStatusResponse").msgclass
  end
end
